name: "Bugs from scratch in molsim-ontology"
description: "General bugs not covered above"
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: input
    id: orcid
    attributes:
      label: "ORCID iD (optional, for dcterms:contributor credit)"
      description: "Enter your ORCID (e.g., 0000-0001-2345-6789) for automatic contributor attribution"
      placeholder: "0000-000X-XXXX-XXXX"
  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "Unexpected behavior, broken links, etc."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
