name: "Typos/Bugs/Errors in molsim-ontology"
description: "Report typos, formatting errors, etc."
title: "[TYPO/BUG] "
labels: ["typo", "bug", "triage"]
body:
  - type: input
    id: orcid
    attributes:
      label: "ORCID iD (optional, for dcterms:contributor credit)"
      description: "Enter your ORCID (e.g., 0000-0001-2345-6789) for automatic contributor attribution"
      placeholder: "0000-000X-XXXX-XXXX"
  - type: textarea
    id: location
    attributes:
      label: "Where (file/line or term ID)"
      placeholder: "src/ontology/molsim-ontology.obo L123"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What you found"
    validations:
      required: true
  - type: textarea
    id: suggested_fix
    attributes:
      label: "Suggested fix (optional)"
